### PR TITLE
Add the required headers and a stub for cchkdf

### PR DESCRIPTION
**Pull request by ahyattdev**
I am not sure if I did enough to not violate the license. Please verify that, some guidelines on what is acceptable and what is not regarding reimplementing corecrypto in the README would be great.

### CODE REVIEW

**Comment by LubosD** [comment]
I'm a little worried about cc_priv.h, because it's an internal implementation detail of Apple's corecrypto - which we really don't need to have in Darling corecrypto for compatibility.

We will however need cchmac first.

**Comment by ahyattdev** [comment]
Understood. What do we need to implement for compatibility? Is there a public set of headers we are using? Is it just things that Security.framework uses?

**Comment by LubosD** [comment]
This is hard to answer :-) The dependencies kind of go in chains, so in order to have recent CommonCrypto, you need to have full CoreCrypto etc.

I think the best thing would be to have sha1 & sha2 digests (I've already added md2/4/5) and hmac and then add stuff as needed.

**Comment by ahyattdev** [comment]
I deleted the worrisome commits (kept a backup of course).

**Pull request closed without merging**
